version: '3'
services:
    client:
        container_name: client
        build:
            context: ./frontend
        ports:
            - 5173:5173
    nginx:
        container_name: nginx
        build: ./frontend/.nginx
        depends_on:
            - client
        volumes:
            - ./frontend/.nginx/conf.d:/etc/nginx/conf.d
            - ./frontend/.nginx/cert:/cert

        ports:
            - 80:80
            - 443:443
