version: "3"
services:
  client:
    container_name: write-fe
    build:
      context: ./frontend
    ports:
      - 3000:3000
  nginx:
    container_name: nginx
    build: ./.nginx
    depends_on:
      - client
    volumes:
      - .nginx/conf.d:/etc/nginx/conf.d
      - .nginx/cert:/cert

    ports:
      - 80:80
      - 443:443
