version: '3'
services:
    client:
        container_name: fe
        build:
            context: ./fe
        ports:
            - 5173:5173
    nginx:
        container_name: nginx
        build: ./.nginx
        depends_on:
            - fe
        volumes:
            - /var/jenkinsDir/workspace/fe/.nginx/conf.d:/etc/nginx/conf.d
            - /var/jenkinsDir/workspace/fe/.nginx/cert:/cert
        ports:
            - 80:80
            - 443:443
