version: '3'
services:
    client:
        container_name: client
        build:
            context: ./frontend
        ports:
            - 5173:5173
    nginx:
        container_name: nginx
        build: ./.nginx
        depends_on:
            - client
        volumes:
            - /var/jenkinsDir/workspace/write-fe/.nginx/conf.d:/etc/nginx/conf.d
            - /var/jenkinsDir/workspace/write-fe/.nginx/cert:/cert
        ports:
            - 80:80
            - 443:443
