pipeline{
    agent any
    
    stages{
        stage('Clone Repo'){
            steps{
                git url: 'https://github.com/wnsdk/write.git',
                    credentialsId: 'github-credential', // Jenkins에서 설정한 credential의 ID
                    branch: 'fe/main'
            }
        }

        stage('Deploy Docker'){
            steps{
                script{
                    sh "ls"
                    sh "docker-compose -f docker-compose.yml pull"
                    sh "COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1"
                    sh "docker-compose -f docker-compose.yml build --no-cache" // 캐시 사용하지 않고 빌드
                    sh "docker-compose -f docker-compose.yml up -d --remove-orphans"
                }
            }
        }

        stage('Finish'){
            steps{
                script{
                    sh "docker rmi -f \$(docker images -f \"dangling=true\" -q) || true"
                }
            }
        }
    }
}
