pipeline{
    agent any
    
    stages{
        stage('Clone Repo'){
            steps{
                git url: 'https://github.com/wnsdk/write.git',
                    credentialsId: 'github-credential', // Jenkins에서 설정한 credential의 ID
                    branch: 'fe/main'
            }
        }

        stage('Deploy Docker'){
            steps{
                script{
                    withCredentials([string(credentialsId: 'openai-api-key', variable: 'OPENAI_API_KEY')]) {
                        sh "ls"
                        sh "docker-compose -f docker-compose.yml pull"
                        sh "COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1"
                        sh "docker-compose -f docker-compose.yml build --no-cache --build-arg VITE_OPENAI_API_KEY=${OPENAI_API_KEY}"
                        // sh "docker-compose run --rm frontend npm run build -- --mode production"
                        sh "docker-compose -f docker-compose.yml up -d --remove-orphans"
                    }
                }
            }
        }

        stage('Finish'){
            steps{
                script{
                    sh "docker rmi -f \$(docker images -f \"dangling=true\" -q) || true"
                }
            }
        }
    }
}
