INSERT INTO prompt (category, mode, title, body) VALUES 
('NOVEL', 'WRITING', 'The Whispering Shadows', 'In a town shrouded in mystery, secrets linger in the whispers of the shadows.'),
('NOVEL', 'COPYING', 'A Journey Through Time', 'A young girl discovers a time portal hidden in her grandmother’s attic.'),
('NOVEL', 'TRANSLATING', 'The Last Forest', 'As civilization expands, the last remaining forest holds secrets that could change everything.'),
('ESSAY', 'WRITING', 'The Impact of Technology on Society', 'Technology has revolutionized the way we live, but at what cost?'),
('ESSAY', 'COPYING', 'Climate Change: A Global Crisis', 'The effects of climate change are evident, and urgent action is needed.'),
('ESSAY', 'TRANSLATING', 'Education in the 21st Century', 'How has education evolved to meet the demands of a changing world?'),
('DIALOGUE', 'WRITING', 'The Coffee Shop Encounter', 'Two strangers meet in a coffee shop, and their conversation reveals more than they expected.'),
('DIALOGUE', 'COPYING', 'A Chat at Midnight', 'Friends discuss their dreams and fears under the stars.'),
('DIALOGUE', 'TRANSLATING', 'The Argument', 'A heated debate between two colleagues leads to unexpected revelations.'),
('INTERVIEW', 'WRITING', 'An Interview with a Visionary', 'A renowned artist discusses their creative process and inspirations.'),
('INTERVIEW', 'COPYING', 'Voices of the Future', 'Young activists share their thoughts on changing the world.'),
('INTERVIEW', 'TRANSLATING', 'The Mind Behind the Masterpiece', 'An exclusive interview with a celebrated author.'),
('LETTER', 'WRITING', 'A Letter to My Future Self', 'What advice would you give to your future self?'),
('LETTER', 'COPYING', 'A Letter from the Past', 'Discovering a letter that reveals family secrets.'),
('LETTER', 'TRANSLATING', 'Words of Encouragement', 'A heartfelt letter to a friend in need.'),
('DIARY', 'WRITING', 'My Day at the Fair', 'A recount of the most thrilling experiences at the local fair.'),
('DIARY', 'COPYING', 'Reflections on a Journey', 'Insights gained during my travels abroad.'),
('DIARY', 'TRANSLATING', 'A Day to Remember', 'Documenting a significant day in my life.'),
('PLAY', 'WRITING', 'The Heart of the City', 'A drama that unfolds in the bustling streets of New York.'),
('PLAY', 'COPYING', 'Secrets of the Manor', 'A murder mystery set in a grand old mansion.'),
('PLAY', 'TRANSLATING', 'The Lost Treasure', 'A comedic adventure about a group searching for hidden treasure.'),
('Editorial', 'WRITING', 'The Role of Media in Society', 'How media influences public opinion and shapes our worldview.'),
('Editorial', 'COPYING', 'The Importance of Community', 'Exploring the value of community in today’s society.'),
('Editorial', 'TRANSLATING', 'Bridging the Generation Gap', 'Understanding the differences between generations and finding common ground.'),
('NOVEL', 'WRITING', 'The Silent Ocean', 'A marine biologist uncovers the secrets of the deep sea.'),
('ESSAY', 'COPYING', 'The Art of Mindfulness', 'How mindfulness can improve mental health and well-being.'),
('DIALOGUE', 'TRANSLATING', 'A Heartfelt Conversation', 'A conversation between a mother and daughter about life choices.'),
('INTERVIEW', 'WRITING', 'The Innovator’s Journey', 'An entrepreneur shares their story of success and failure.'),
('LETTER', 'COPYING', 'A Note of Gratitude', 'Expressing appreciation for the small things in life.'),
('DIARY', 'TRANSLATING', 'A Week of Adventures', 'A summary of my week filled with new experiences.'),
('PLAY', 'WRITING', 'The Last Train Home', 'A poignant story about connections made on a train journey.'),
('Editorial', 'COPYING', 'The Future of Education', 'A discussion on the evolving landscape of education in the digital age.');
