jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

logging:
  level:
    org:
      springframework: DEBUG

server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ENC(oSnEdzfDZdJsKAVr7HRHkbJgKIK/XZje)
    key-store-type: PKCS12
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/write
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create  # or create, create-drop, validate based on your needs
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
