spring:
  application:
    name: write
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create # create, create-drop, update, validate
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
  data:
    redis:
      host: localhost
      port: 6379

#redirect:
#  uri: /login/oauth2/code/*