server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ENC(XZSEKgSvYhG1jlhaPsW7OQ==)
    key-store-type: PKCS12
    enabled: true
  servlet:
    context-path: /api
  use-forward-headers: true

logging:
  level:
    org:
      springframework: DEBUG

spring:
#  datasource:
#    url: jdbc:mysql://mysql:3306/write
#    username: root
#    password: root
  datasource:
    url: jdbc:h2:tcp://h2:1521/test;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create  # or create, create-drop, validate based on your needs
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: https://www.usewrite.site/api/login/oauth2/code/google
    data:
      redis:
        host: redis
        port: 6379
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}