spring:
  datasource:
    url: jdbc:mysql://localhost:3306/write_db
    username: write
    password: write
  jpa:
    hibernate:
      ddl-auto: create  # or create, create-drop, validate based on your needs
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
test: prod

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
